export class AppError extends Error {
  public readonly statusCode: number;
  public readonly code: string;
  public readonly details?: any;

  constructor(statusCode: number, code: string, message: string, details?: any) {
    super(message);
    this.statusCode = statusCode;
    this.code = code;
    this.details = details;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export const ErrorCodes = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ENROLLMENT_NOT_FOUND: "ENROLLMENT_NOT_FOUND",
  MODULE_LOCKED: "MODULE_LOCKED",
  MODULE_NOT_STARTED: "MODULE_NOT_STARTED",
  MODULE_NOT_AVAILABLE: "MODULE_NOT_AVAILABLE",
  MODULE_EXPIRED: "MODULE_EXPIRED",
  PREVIOUS_LESSONS_INCOMPLETE: "PREVIOUS_LESSONS_INCOMPLETE",
  PREVIOUS_QUIZ_MISSING: "PREVIOUS_QUIZ_MISSING",
  PREVIOUS_QUIZ_FAILED: "PREVIOUS_QUIZ_FAILED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  QUIZ_NOT_FOUND: "QUIZ_NOT_FOUND",
  QUIZ_MAX_ATTEMPTS_REACHED: "QUIZ_MAX_ATTEMPTS_REACHED",
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  LIVE_SESSION_NOT_FOUND: "LIVE_SESSION_NOT_FOUND",
  GOOGLE_AUTH_REQUIRED: "GOOGLE_AUTH_REQUIRED",
  GOOGLE_CALENDAR_ERROR: "GOOGLE_CALENDAR_ERROR",
  COHORT_NOT_FOUND: "COHORT_NOT_FOUND",
  INVALID_ENROLLMENT_STATUS: "INVALID_ENROLLMENT_STATUS",
  VIDEO_ACCESS_DENIED: "VIDEO_ACCESS_DENIED",
  LIVE_SESSION_ACCESS_DENIED: "LIVE_SESSION_ACCESS_DENIED",
  APPLICATION_NOT_ACCEPTED: "APPLICATION_NOT_ACCEPTED",
  WEBHOOK_IDEMPOTENT_IGNORED: "WEBHOOK_IDEMPOTENT_IGNORED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
